# Generated by Django 5.1.6 on 2025-03-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
