# Generated by Django 5.1.6 on 2025-03-04 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unet', '0007_mention'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='retweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retweets', to='Unet.post'),
        ),
    ]
